### ISSUE TITLE
某知笔记服务端docker镜像授权分析 | 半块西瓜皮的博客

### ISSUE THREAD

**Issue by howmp** [howmp/Gitalk#8]
https://guage.cool/wiz-license/ 

 某知笔记服务端docker镜像授权分析

**Comment by kaka77** [comment]
大佬，求crack补丁 : )

**Comment by howmp** [comment]
> @kaka77
> 大佬，求crack补丁 : ) 

保存成docker-compose.yaml，并在当前目录放上修改后的NodeRSA.js

```yaml
version: '3'

services:
  wiz:
    image: wiznote/wizserver
    restart: unless-stopped
    volumes:
      - ./wizdata:/wiz/storage 
      - /etc/localtime:/etc/localtime
      - ./NodeRSA.js:/wiz/app/wizserver/node_modules/node-rsa/src/NodeRSA.js
    ports:
      - "80:80"
      - "9269:9269/udp"
```
